// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@20.19.30_@vue+compiler-sfc@3.5.26_cac@6.7_13168a1e98214854cd97931babb1e3fe/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@20.19.30_@vue+compiler-sfc@3.5.26_cac@6.7_13168a1e98214854cd97931babb1e3fe/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@20.19.30_@vue+compiler-sfc@3.5.26_cac@6.7_13168a1e98214854cd97931babb1e3fe/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@20.19.30_@vue+compiler-sfc@3.5.26_cac@6.7_13168a1e98214854cd97931babb1e3fe/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@20.19.30_@vue+compiler-sfc@3.5.26_cac@6.7_13168a1e98214854cd97931babb1e3fe/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@20.19.30_@vue+compiler-sfc@3.5.26_cac@6.7_13168a1e98214854cd97931babb1e3fe/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@20.19.30_@vue+compiler-sfc@3.5.26_cac@6.7_13168a1e98214854cd97931babb1e3fe/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@20.19.30_@vue+compiler-sfc@3.5.26_cac@6.7_13168a1e98214854cd97931babb1e3fe/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@20.19.30_@vue+compiler-sfc@3.5.26_cac@6.7_13168a1e98214854cd97931babb1e3fe/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@20.19.30_@vue+compiler-sfc@3.5.26_cac@6.7_13168a1e98214854cd97931babb1e3fe/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@20.19.30_@vue+compiler-sfc@3.5.26_cac@6.7_13168a1e98214854cd97931babb1e3fe/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@20.19.30_@vue+compiler-sfc@3.5.26_cac@6.7_13168a1e98214854cd97931babb1e3fe/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@20.19.30_@vue+compiler-sfc@3.5.26_cac@6.7_13168a1e98214854cd97931babb1e3fe/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
